version: "3.8"

services:
  app:
    image: landing-page:v1
    container_name: landing-page
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    restart: always
